### ISSUE TITLE
CentOS 8 Support tracker

### ISSUE THREAD

**Issue by hairmare** [radiorabe/centos-rpm-openob#2]
* [ ] Bump to 4.x OpenOB for gst-1.0 support
* [ ] Recompile (or find) working gstreamer-python bindings (they won't compile due to missing gstreamer-dataprotocol things in upstreams gstreamer1-devel package).
* [ ] Check if Python3 is possible
* [ ] Test if 4.x still works on CentOS 7
* [ ] Patch Specfile to support CentOS 7 alongside 8
